#ifndef __spinachoptionFrameBase__
#define __spinachoptionFrameBase__

/**
@file
Subclass of optionFrameBase, which is generated by wxFormBuilder.
*/

#include "spinachGUI.h"

/** Implementing optionFrameBase */
class optionFrame : public optionFrameBase
{
public:
	/** Constructor */
	optionFrame( wxWindow* parent );
};

#endif // __spinachoptionFrameBase__
