#ifndef __rootFrame__
#define __rootFrame__

#include <boost/scoped_ptr.hpp>

#include <wx/odcombo.h>
#include <wx/propgrid/propgrid.h>
//#include <wx/propgrid/advprops.h>

#include <gui/spinachGUI.h>
#include <gui/optionFrame.h>
#include <gui/calcFrame.h>

#include <shared/spin_system.h>

using namespace boost;

enum {
    EV_MODE_SHIELDING=1,
    EV_MODE_JCOUPLING,
    EV_MODE_CLUSTERS,
    EV_FOCUSED_SPIN_CHANGE,
    EV_SPIN_PROP_GRID_CHANGE
};

/*
rootFrameBase is generated by wxFormBuilder. rootFrame inherits
rootFrameBase's properties


In order for this to compile, wxUSE_GLCANVAS must
be set to 1 in wxWidgets-2.8.9\lib\gcc_lib\mswd\wx\setup.h

*/

class glMolDisplay;  //Resolve the cyclic dependency by replying on the fact that all pointers are alike
class SpinPropertyGrid;

class rootFrame : public rootFrameBase
{
public:

	rootFrame(wxWindow* parent);

  //Event Handling functions
    void OnIdle(wxIdleEvent& e);
    void ShowOptions(wxCommandEvent& e);
    void ShowCalc(wxCommandEvent& e);
    void OnMouseMove(wxMouseEvent& e);

    void setModeShielding(wxCommandEvent& e);
    void setModeJCoupling(wxCommandEvent& e);
    void setModeClusters(wxCommandEvent& e);

    void onFocusedSpinChange(wxCommandEvent& e);
    //void onSpinPropGridChange(wxPropertyGridEvent& e);

  //Graphics functions
	void enableGL();
	void glTick();

  //Functions for interacting with the spin system
    void SetFocusedSpin(long index);   //Focus on a particular spin, updating the properties pannel.
    unsigned long GetFocusedSpin();   //Focus on a particular spin, updating the properties pannel.

  //Functions for updating the contained spin system
    void addSpin(SpinPnt S);

  //Numerical Stuff
    scoped_ptr<SpinSystem> mSpinSys;

protected:
    void popCouplingGrid();

    unsigned long mActiveSpin;  //The index of the currently selected spin

    SpinPropertyGrid* mSpinPropGrid;
	wxPropertyGrid* mCouplingPropGrid;
    glMolDisplay* mMolDisplay;


    DECLARE_EVENT_TABLE()

};

#endif // __rootFrame__
