#ifndef __rootFrame__
#define __rootFrame__

#include <boost/scoped_ptr.hpp>

#include <wx/odcombo.h>
#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/advprops.h>

#include "spinachGUI.h"
#include "optionFrame.h"
#include "calcFrame.h"
#include "glMolDisplay.h"

#include "../shared/struct.h"

using namespace boost;

enum {
    EV_MODE_SHIELDING=1,
    EV_MODE_JCOUPLING,
    EV_MODE_CLUSTERS
};

/*
rootFrameBase is generated by wxFormBuilder. rootFrame inherits
rootFrameBase's properties


In order for this to compile, wxUSE_GLCANVAS must
be set to 1 in wxWidgets-2.8.9\lib\gcc_lib\mswd\wx\setup.h

*/

class rootFrame : public rootFrameBase
{
public:

	rootFrame(wxWindow* parent);

  //Event Handling functions
    void OnIdle(wxIdleEvent& e);
    void ShowOptions(wxCommandEvent& e);
    void ShowCalc(wxCommandEvent& e);
    void OnMouseMove(wxMouseEvent& e);

    void setModeShielding(wxCommandEvent& e);
    void setModeJCoupling(wxCommandEvent& e);
    void setModeClusters(wxCommandEvent& e);

  //Graphics functions
	void enableGL();
	void glTick();

protected:
    void popSpinPropGrid();
    void popCouplingGrid();

    wxPropertyGrid* mSpinPropGrid;
	wxPropertyGrid* mCouplingPropGrid;
    glMolDisplay* mMolDisplay;

  //Numerical Stuff
    scoped_ptr<SpinSystem> mSpinSys;

    DECLARE_EVENT_TABLE()

};

#endif // __rootFrame__
