#ifndef __spinachcalcFrameBase__
#define __spinachcalcFrameBase__

/**
@file
Subclass of calcFrameBase, which is generated by wxFormBuilder.
*/

#include "spinachGUI.h"

/** Implementing calcFrameBase */
class calcFrame : public calcFrameBase
{
public:
	/** Constructor */
	calcFrame( wxWindow* parent );
};

#endif // __spinachcalcFrameBase__
