#ifndef __rootFrame__
#define __rootFrame__

#include <gl/gl.h>
#include <wx/glcanvas.h>
#include <wx/odcombo.h>

#include "spinachGUI.h"
#include "optionFrame.h"
#include "calcFrame.h"

/*
rootFrameBase is generated by wxFormBuilder. rootFrame inherits
rootFrameBase's properties


In order for this to compile, wxUSE_GLCANVAS must
be set to 1 in wxWidgets-2.8.9\lib\gcc_lib\mswd\wx\setup.h

*/
class rootFrame : public rootFrameBase
{
public:

	rootFrame(wxWindow* parent);

  //Event Handling functions
    void OnIdle(wxIdleEvent& e);
    void ShowOptions(wxCommandEvent& e);
    void ShowCalc(wxCommandEvent& e);

  //Graphics functions
	void enableGL();
	void glTick();

protected:
    wxGLCanvas* mGLCanvas;
    DECLARE_EVENT_TABLE()

};

#endif // __rootFrame__
